apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-pages
  labels:
    app: nextjs-pages
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextjs-pages
  template:
    metadata:
      labels:
        app: nextjs-pages
    spec:
      containers:
      - name: nextjs-pages
        image: nextjs-pages
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
      restartPolicy: Always
