apiVersion: v1
kind: Service
metadata:
  name: nextjs-pages
  namespace: nextjs-pages
  labels:
    app: nextjs-pages
spec:
  type: ClusterIP
  selector:
    app: nextjs-pages
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
